### ISSUE TITLE
Zapret ubuntu

### ISSUE THREAD

**Issue by pvmigdalov** [0x201/YouTube#1]
Zapret на ubuntu не взлетел. Провайдер билайн

**Comment by IamWavelet** [comment]
Здравствуйте, здесь я вряд ли смогу помочь, т.к. у меня провайдором является **МГТС**, который по ощущениям наиболее жесткий в блокировках. Но могу дать наводку на issue "zapret", где обсуждают актуальные стратегии обхода DPI (в основном для YouTube). Перейдите по ссылке ниже и пролистайте до конца и возможно щедрые люди уже рассказали актуальные методы обхода блокировок, а если не сработает, задайте там вопрос. Ну а если же и этот вариант не оправдает себя, то тут получится разве что методом тыка, взяв в руки документацию по параметрам "zapret", и вперед подбирать конфиг. Рекомендую поставить кучу параметров, чтобы ТСПУ было сложно копаться в этой горе мусора. И ещё могу порекомендовать взять чей либо конфиг и доработать под свои нужды, ведь сначала создавать свой, требует затраты времени. Надеюсь помог.

Issue zapret: https://github.com/bol-van/zapret/discussions/200


Параметры тут: https://github.com/bol-van/zapret/blob/master/docs/readme.txt
